---
- name: Restart netfilter-persistent
  ansible.builtin.service:
    name: netfilter-persistent
    state: restarted

- name: Reload haproxy
  ansible.builtin.command: haproxy -c -f /etc/haproxy/haproxy.cfg
  notify:
    - Reload checked haproxy

- name: Reload checked haproxy
  ansible.builtin.service:
    name: haproxy
    state: reloaded

- name: Restart syslog-ng
  ansible.builtin.service:
    name: syslog-ng
    state: restarted
